### ISSUE TITLE
이 코드 최적화 해주세요!

### ISSUE THREAD

**Issue by devops-04-DoHyeon** [Mmuseng/JS_Study#2]
function findShortestOfThreeWords(word1, word2, word3) {
    let parameters = [word1, word2, word3];
    let shortest = parameters[0];

    for ( i = 1 ; i < parameters.length ; i++ ){
        if(shortest.length > parameters[i].length){
            shortest = parameters[i];
        } 
    }
    return shortest;
}
![1](https://user-images.githubusercontent.com/124059491/225790853-403be8ba-e752-4593-b19d-1e606a194cdf.PNG)

**Comment by hansungmoon** [comment]
function findShortestOfThreeWords(word1, word2, word3) {
  // Define the list of pairs
  const pairs = [
    [word1.length, word1],
    [word2.length, word2],
    [word3.length, word3],
  ];

  // Sort the list by the key in ascending order
  pairs.sort((a, b) => a[0] - b[0]);

  const smallestItem = pairs[0];
  return smallestItem[1];
}
